import type { Metadata } from "next";
import { Building2, Mail, MapPin, Phone, Send } from "lucide-react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "ติดต่อเรา", description: "ช่องทางติดต่อราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย" };

export default function ContactPage() {
  return <><SiteHeader /><main><section className="bg-[var(--secondary)] py-14 sm:py-20"><div className="container-shell max-w-4xl"><p className="eyebrow mb-3">CONTACT RCOPT</p><h1 className="section-title text-3xl sm:text-5xl">ติดต่อเรา</h1><p className="mt-5 max-w-2xl text-base leading-8 text-[var(--muted)]">หากมีข้อสงสัยหรือต้องการสอบถามข้อมูลเพิ่มเติม สามารถติดต่อราชวิทยาลัยจักษุแพทย์แห่งประเทศไทยผ่านช่องทางด้านล่าง</p></div></section><section className="container-shell grid gap-6 py-14 lg:grid-cols-[1.1fr_.9fr] sm:py-20"><div className="card p-7 sm:p-9"><div className="mb-7 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--primary-light)] text-[var(--primary)]"><Building2 size={21} /></span><div><h2 className="text-xl font-extrabold">สำนักงานราชวิทยาลัยฯ</h2><p className="text-sm text-[var(--muted)]">The Royal College of Ophthalmologists of Thailand</p></div></div><dl className="grid gap-6 text-sm leading-7 text-[var(--muted)]"><div className="flex gap-3"><MapPin className="mt-1 shrink-0 text-[var(--primary)]" size={18} /><div><dt className="font-bold text-[var(--ink)]">ที่อยู่</dt><dd>ชั้น 10 อาคารเฉลิมพระบารมี 50 ปี<br />2 ซอยศูนย์วิจัย ถนนเพชรบุรีตัดใหม่<br />แขวงบางกะปิ เขตห้วยขวาง กรุงเทพมหานคร 10310</dd></div></div><div className="flex gap-3"><Phone className="mt-1 shrink-0 text-[var(--primary)]" size={18} /><div><dt className="font-bold text-[var(--ink)]">โทรศัพท์ / โทรสาร</dt><dd><a className="hover:text-[var(--primary-dark)]" href="tel:+6627180715">02 718 0715–6</a><br />โทรสาร 02 718 0717</dd></div></div><div className="flex gap-3"><Mail className="mt-1 shrink-0 text-[var(--primary)]" size={18} /><div><dt className="font-bold text-[var(--ink)]">อีเมล</dt><dd><a className="font-bold text-[var(--primary-dark)] hover:underline" href="mailto:admin@rcopt.org">admin@rcopt.org</a></dd></div></div></dl></div><aside className="rounded-3xl bg-[#3a202d] p-7 text-white sm:p-9"><p className="eyebrow !text-[#f4a6c3]">GET IN TOUCH</p><h2 className="mt-3 text-2xl font-extrabold">ส่งข้อความถึงเรา</h2><p className="mt-4 text-sm leading-7 text-[#f3dce5]">ระบบเดิมใช้ฟอร์มติดต่อผ่านอีเมล คุณสามารถเริ่มส่งข้อความถึงทีมงานได้โดยตรงผ่านโปรแกรมอีเมลของคุณ</p><a href="mailto:admin@rcopt.org?subject=ติดต่อราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย" className="mt-7 inline-flex items-center justify-center rounded-xl bg-[var(--primary)] px-5 py-3 text-sm font-bold text-white shadow-lg hover:bg-[var(--primary-dark)]"><Send className="mr-2" size={17} />ส่งอีเมลถึง RCOPT</a><p className="mt-7 border-t border-white/15 pt-5 text-xs leading-6 text-[#f3dce5]">กรุณาไม่ส่งข้อมูลสุขภาพส่วนบุคคลหรือข้อมูลผู้ป่วยทางอีเมล</p></aside></section></main><SiteFooter /></>;
}
