"use server";
import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { env } from "@/lib/env";
import { requireAdminWrite } from "@/lib/admin-write";
import { clientAddress } from "@/lib/public-request-protection";
import { isTrustedRequestOrigin } from "@/lib/request-origin";
import { deleteAdminArticle, deleteArticleCategory, deleteBoardCategory, deleteBoardTopic, deleteSiteMenu, saveAdminArticle, saveBoardCategory, saveCategory, saveMenu, saveTopic } from "@/repositories/admin-cms-repository";

const id=z.coerce.number().int().positive(); const optionalId=z.preprocess(v=>v===""?undefined:v,id.optional()); const text=(n:number)=>z.string().trim().max(n);
function notice(path:string,type:"success"|"error",message:string):never { redirect(`${path}?${type}=${encodeURIComponent(message)}`); }
async function context(){const h=await headers();if(!isTrustedRequestOrigin(h,[new URL(env.SITE_URL).host]))throw new Error("BAD_ORIGIN");return {admin:await requireAdminWrite(),address:clientAddress(h)}}
function yes(v:FormDataEntryValue|null){return v==="yes"}
async function articleImage(file:File){if(!env.LEGACY_UPLOAD_PATH||file.size<1||file.size>3*1024*1024)throw new Error("INVALID_IMAGE");const ext=path.extname(file.name).toLowerCase();if(!new Set([".jpg",".jpeg",".png",".gif",".webp"]).has(ext)||!file.type.startsWith("image/"))throw new Error("INVALID_IMAGE");const data=Buffer.from(await file.arrayBuffer());const valid=(ext===".jpg"||ext===".jpeg")?data.subarray(0,3).equals(Buffer.from([255,216,255])):ext===".png"?data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):ext===".gif"?["GIF87a","GIF89a"].includes(data.subarray(0,6).toString("ascii")):data.subarray(0,4).toString("ascii")==="RIFF"&&data.subarray(8,12).toString("ascii")==="WEBP";if(!valid)throw new Error("INVALID_IMAGE");const filename=`article-${randomUUID()}${ext}`;const dir=path.join(env.LEGACY_UPLOAD_PATH,"uploads");await mkdir(dir,{recursive:true});await writeFile(path.join(dir,filename),data,{flag:"wx"});return filename}

export async function saveArticle(formData:FormData){const p=z.object({id:optionalId,title:text(1000).min(1),intro:text(20000),body:text(500000),categoryId:id}).safeParse(Object.fromEntries(formData));if(!p.success)notice("/admin/articles","error","กรุณากรอกหัวข้อ เนื้อหา และหมวดหมู่ให้ถูกต้อง");try{const upload=formData.get("image");const image=upload instanceof File&&upload.size?await articleImage(upload):undefined;const {admin,address}=await context();const articleId=await saveAdminArticle({...p.data,imagePath:image,published:yes(formData.get("published")),featured:yes(formData.get("featured")),sortFirst:yes(formData.get("sortFirst")),actorId:admin.userId,address});revalidatePath("/");revalidatePath("/articles");revalidatePath("/news");revalidatePath(`/articles/${articleId}`);}catch{notice("/admin/articles","error","ไม่สามารถบันทึกบทความได้ กรุณาตรวจสอบข้อมูลและไฟล์รูปภาพ")}notice("/admin/articles","success",p.data.id?"บันทึกการแก้ไขบทความแล้ว":"เพิ่มบทความแล้ว")}
export async function saveArticleCategory(formData:FormData){const p=z.object({id:optionalId,name:text(45).min(1),description:text(20000)}).safeParse(Object.fromEntries(formData));if(!p.success)notice("/admin/categories","error","กรุณาระบุชื่อหมวดหมู่");try{const {admin,address}=await context();await saveCategory({...p.data,actorId:admin.userId,address});revalidatePath("/articles");revalidatePath("/admin/categories");}catch{notice("/admin/categories","error","ไม่สามารถบันทึกหมวดหมู่ได้")}notice("/admin/categories","success",p.data.id?"บันทึกหมวดหมู่แล้ว":"เพิ่มหมวดหมู่แล้ว")}
export async function saveSiteMenu(formData:FormData){const p=z.object({id:optionalId,parentId:z.coerce.number().int().min(0),title:text(35).min(1),position:z.coerce.number().int().min(0).max(9999),tooltip:text(100),url:text(255),icon:text(50),task:text(64),options:text(100)}).safeParse(Object.fromEntries(formData));if(!p.success)notice("/admin/menu","error","กรุณาระบุชื่อเมนูและข้อมูลให้ถูกต้อง");try{const {admin,address}=await context();await saveMenu({...p.data,visible:yes(formData.get("visible")),actorId:admin.userId,address});revalidatePath("/");revalidatePath("/admin/menu");}catch{notice("/admin/menu","error","ไม่สามารถบันทึกเมนูได้")}notice("/admin/menu","success",p.data.id?"บันทึกเมนูแล้ว":"เพิ่มเมนูแล้ว")}
export async function saveWebboardCategory(formData:FormData){const p=z.object({id:optionalId,name:text(45).min(1),description:text(20000)}).safeParse(Object.fromEntries(formData));if(!p.success)notice("/admin/webboard","error","กรุณาระบุชื่อกลุ่มหัวข้อ");try{const {admin,address}=await context();await saveBoardCategory({...p.data,actorId:admin.userId,address});revalidatePath("/community/questions");revalidatePath("/admin/webboard");}catch{notice("/admin/webboard","error","ไม่สามารถบันทึกกลุ่มหัวข้อได้")}notice("/admin/webboard","success",p.data.id?"บันทึกกลุ่มหัวข้อแล้ว":"เพิ่มกลุ่มหัวข้อแล้ว")}
export async function saveWebboardTopic(formData:FormData){const p=z.object({id:optionalId,title:text(255).min(1),body:text(20000),categoryId:id}).safeParse(Object.fromEntries(formData));if(!p.success)notice("/admin/webboard","error","กรุณาระบุหัวข้อและกลุ่มหัวข้อให้ถูกต้อง");try{const {admin,address}=await context();await saveTopic({...p.data,enabled:yes(formData.get("enabled")),actorId:admin.userId,address});revalidatePath("/community/questions");revalidatePath("/admin/webboard");}catch{notice("/admin/webboard","error","ไม่สามารถบันทึกหัวข้อ Webboard ได้")}notice("/admin/webboard","success",p.data.id?"บันทึกหัวข้อ Webboard แล้ว":"เพิ่มหัวข้อ Webboard แล้ว")}
async function remove(formData:FormData,fn:(v:{id:number;actorId:number;address:string})=>Promise<void>,paths:string[],target:string,message:string){const p=id.safeParse(formData.get("id"));if(!p.success)notice(target,"error","ไม่พบรายการที่ต้องการลบ");try{const {admin,address}=await context();await fn({id:p.data,actorId:admin.userId,address});paths.forEach((value)=>revalidatePath(value));}catch{notice(target,"error","ไม่สามารถลบรายการได้ เพราะอาจมีข้อมูลอื่นอ้างอิงอยู่")}notice(target,"success",message)}
export async function deleteArticle(f:FormData){await remove(f,deleteAdminArticle,["/","/articles","/news","/admin/articles"],"/admin/articles","ลบบทความแล้ว")}
export async function deleteCategory(f:FormData){await remove(f,deleteArticleCategory,["/articles","/admin/categories"],"/admin/categories","ลบหมวดหมู่แล้ว")}
export async function deleteMenu(f:FormData){await remove(f,deleteSiteMenu,["/","/admin/menu"],"/admin/menu","ลบเมนูแล้ว")}
export async function deleteWebboardCategory(f:FormData){await remove(f,deleteBoardCategory,["/community/questions","/admin/webboard"],"/admin/webboard","ลบกลุ่มหัวข้อแล้ว")}
export async function deleteWebboardTopic(f:FormData){await remove(f,deleteBoardTopic,["/community/questions","/admin/webboard"],"/admin/webboard","ลบหัวข้อและคำตอบแล้ว")}
