"use server";
import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { env } from "@/lib/env";
import { requireAdminWrite } from "@/lib/admin-write";
import { clientAddress } from "@/lib/public-request-protection";
import { isTrustedRequestOrigin } from "@/lib/request-origin";
import { deleteAdminArticle, deleteArticleCategory, deleteBoardCategory, deleteBoardTopic, deleteSiteMenu, saveAdminArticle, saveBoardCategory, saveCategory, saveMenu, saveTopic } from "@/repositories/admin-cms-repository";
const id=z.coerce.number().int().positive();const optionalId=z.preprocess(v=>v===""?undefined:v,id.optional());const text=(n:number)=>z.string().trim().max(n);
async function context(){const h=await headers();if(!isTrustedRequestOrigin(h,[new URL(env.SITE_URL).host]))throw new Error("BAD_ORIGIN");return {admin:await requireAdminWrite(),address:clientAddress(h)}}
function yes(v:FormDataEntryValue|null){return v==="yes"}
async function articleImage(file:File){if(!env.LEGACY_UPLOAD_PATH||file.size<1||file.size>3*1024*1024)throw new Error("INVALID_IMAGE");const ext=path.extname(file.name).toLowerCase();if(!new Set([".jpg",".jpeg",".png",".gif",".webp"]).has(ext)||!file.type.startsWith("image/"))throw new Error("INVALID_IMAGE");const data=Buffer.from(await file.arrayBuffer());const valid=(ext===".jpg"||ext===".jpeg")?data.subarray(0,3).equals(Buffer.from([255,216,255])):ext===".png"?data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):ext===".gif"?["GIF87a","GIF89a"].includes(data.subarray(0,6).toString("ascii")):data.subarray(0,4).toString("ascii")==="RIFF"&&data.subarray(8,12).toString("ascii")==="WEBP";if(!valid)throw new Error("INVALID_IMAGE");const filename=`article-${randomUUID()}${ext}`;const dir=path.join(env.LEGACY_UPLOAD_PATH,"uploads");await mkdir(dir,{recursive:true});await writeFile(path.join(dir,filename),data,{flag:"wx"});return filename}
export async function saveArticle(formData:FormData){const p=z.object({id:optionalId,title:text(1000).min(1),intro:text(20000),body:text(500000),categoryId:id}).safeParse(Object.fromEntries(formData));if(!p.success)throw new Error("INVALID_INPUT");const upload=formData.get("image");const image=upload instanceof File&&upload.size?await articleImage(upload):undefined;const {admin,address}=await context();const articleId=await saveAdminArticle({...p.data,imagePath:image,published:yes(formData.get("published")),featured:yes(formData.get("featured")),sortFirst:yes(formData.get("sortFirst")),actorId:admin.userId,address});revalidatePath("/");revalidatePath("/articles");revalidatePath("/news");revalidatePath(`/articles/${articleId}`);redirect("/admin/articles")}
export async function saveArticleCategory(formData:FormData){const p=z.object({id:optionalId,name:text(45).min(1),description:text(20000)}).safeParse(Object.fromEntries(formData));if(!p.success)throw new Error("INVALID_INPUT");const {admin,address}=await context();await saveCategory({...p.data,actorId:admin.userId,address});revalidatePath("/articles");revalidatePath("/admin/categories");redirect("/admin/categories")}
export async function saveSiteMenu(formData:FormData){const p=z.object({id:optionalId,parentId:z.coerce.number().int().min(0),title:text(35).min(1),position:z.coerce.number().int().min(0).max(9999),tooltip:text(100),url:text(255),icon:text(50),task:text(64),options:text(100)}).safeParse(Object.fromEntries(formData));if(!p.success)throw new Error("INVALID_INPUT");const {admin,address}=await context();await saveMenu({...p.data,visible:yes(formData.get("visible")),actorId:admin.userId,address});revalidatePath("/");revalidatePath("/admin/menu");redirect("/admin/menu")}
export async function saveWebboardCategory(formData:FormData){const p=z.object({id:optionalId,name:text(45).min(1),description:text(20000)}).safeParse(Object.fromEntries(formData));if(!p.success)throw new Error("INVALID_INPUT");const {admin,address}=await context();await saveBoardCategory({...p.data,actorId:admin.userId,address});revalidatePath("/community/questions");revalidatePath("/admin/webboard");redirect("/admin/webboard")}
export async function saveWebboardTopic(formData:FormData){const p=z.object({id:optionalId,title:text(255).min(1),body:text(20000),categoryId:id}).safeParse(Object.fromEntries(formData));if(!p.success)throw new Error("INVALID_INPUT");const {admin,address}=await context();await saveTopic({...p.data,enabled:yes(formData.get("enabled")),actorId:admin.userId,address});revalidatePath("/community/questions");revalidatePath("/admin/webboard");redirect("/admin/webboard")}
async function remove(formData:FormData,fn:(v:{id:number;actorId:number;address:string})=>Promise<void>,paths:string[]){const p=id.safeParse(formData.get("id"));if(!p.success)throw new Error("INVALID_INPUT");const {admin,address}=await context();await fn({id:p.data,actorId:admin.userId,address});paths.forEach((value)=>revalidatePath(value))}
export async function deleteArticle(formData:FormData){await remove(formData,deleteAdminArticle,["/","/articles","/news","/admin/articles"]);redirect("/admin/articles")}
export async function deleteCategory(formData:FormData){await remove(formData,deleteArticleCategory,["/articles","/admin/categories"]);redirect("/admin/categories")}
export async function deleteMenu(formData:FormData){await remove(formData,deleteSiteMenu,["/","/admin/menu"]);redirect("/admin/menu")}
export async function deleteWebboardCategory(formData:FormData){await remove(formData,deleteBoardCategory,["/community/questions","/admin/webboard"]);redirect("/admin/webboard")}
export async function deleteWebboardTopic(formData:FormData){await remove(formData,deleteBoardTopic,["/community/questions","/admin/webboard"]);redirect("/admin/webboard")}
