import { connection } from "next/server";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { db } from "@/lib/db";
import { normalizePagination } from "@/lib/pagination";
import { writeLegacyAudit } from "@/lib/admin-write";

export async function listAdminMenuRoots() { await connection(); const [rows] = await db.query<(RowDataPacket & { id:number; title:string })[]>("SELECT id,title FROM syadm001 WHERE parent_id=0 ORDER BY position,id"); return rows.map((row) => ({ id: Number(row.id), title: String(row.title) })); }
export async function listAdminMenuTree(input:{page:number}) { await connection(); const [rows] = await db.query<(RowDataPacket & AdminMenu)[]>("SELECT id,parent_id parentId,title,position,tooltip,url,icon,visible,task,options FROM syadm001 ORDER BY parent_id,position,id"); const all=rows.map(r=>({id:+r.id,parentId:+r.parentId,title:String(r.title),position:+r.position,tooltip:String(r.tooltip??""),url:String(r.url??""),icon:String(r.icon??""),visible:+r.visible===1,task:String(r.task??""),options:String(r.options??"")})); const roots=all.filter((item)=>item.parentId===0); const p=normalizePagination(input.page,10,50); const selectedRoots=roots.slice(p.offset,p.offset+p.pageSize); const selected=new Set(selectedRoots.map((item)=>item.id)); let changed=true; while(changed){changed=false; for(const item of all) if(selected.has(item.parentId)&&!selected.has(item.id)){selected.add(item.id);changed=true;} } return {total:roots.length,rows:all.filter((item)=>selected.has(item.id))}; }
export type AdminCategory = { id: number; name: string; description: string; count: number };
export type AdminMenu = { id: number; parentId: number; title: string; position: number; tooltip: string; url: string; icon: string; visible: boolean; task: string; options: string };
export type AdminTopic = { id: number; title: string; body: string; categoryId: number; categoryName: string; enabled: boolean; replies: number; views: number; createdAt: string };
export type AdminArticle = { id: number; title: string; intro: string; body: string; categoryId: number; imagePath: string; published: boolean; featured: boolean; sortFirst: boolean };
const page = (value: number) => normalizePagination(value, 25, 50);

export async function listAdminCategories() { await connection(); const [rows] = await db.query<(RowDataPacket & { id:number; name:string; dsca:string|null; nmar:number })[]>("SELECT id,name,dsca,nmar FROM arcat010 ORDER BY id"); return rows.map(r=>({id:+r.id,name:String(r.name),description:String(r.dsca??""),count:+r.nmar})); }
export async function listAdminMenus(input:{page:number}) { await connection(); const p=page(input.page); const [[count], [rows]] = await Promise.all([db.query<RowDataPacket[]>("SELECT COUNT(*) total FROM syadm001"),db.query<(RowDataPacket & AdminMenu)[]>(`SELECT id,parent_id parentId,title,position,tooltip,url,icon,visible,task,options FROM syadm001 ORDER BY parent_id,position,id LIMIT ${p.pageSize} OFFSET ${p.offset}`)]); return {total:+count[0]?.total||0,rows:rows.map(r=>({id:+r.id,parentId:+r.parentId,title:String(r.title),position:+r.position,tooltip:String(r.tooltip??""),url:String(r.url??""),icon:String(r.icon??""),visible:+r.visible===1,task:String(r.task??""),options:String(r.options??"")}))}; }
export async function listAdminTopics(input:{page:number}) { await connection(); const p=page(input.page); const [[count], [rows]] = await Promise.all([db.query<RowDataPacket[]>("SELECT COUNT(*) total FROM wbtpc010"),db.query<(RowDataPacket & {id:number;title:string;body:string;categoryId:number;categoryName:string;enabled:string;replies:number;views:number;createdAt:string})[]>(`SELECT t.id,t.name title,t.dsca body,t.wbcat010_id categoryId,c.name categoryName,t.enbl enabled,t.nmmg replies,t.hits views,t.crdt createdAt FROM wbtpc010 t INNER JOIN wbcat010 c ON c.id=t.wbcat010_id ORDER BY t.lmdt DESC,t.id DESC LIMIT ${p.pageSize} OFFSET ${p.offset}`)]); return {total:+count[0]?.total||0,rows:rows.map(r=>({id:+r.id,title:String(r.title),body:String(r.body??""),categoryId:+r.categoryId,categoryName:String(r.categoryName),enabled:r.enabled==="Yes",replies:+r.replies,views:+r.views,createdAt:String(r.createdAt)}))}; }
export async function listAdminBoardCategories() { await connection(); const [rows]=await db.query<(RowDataPacket & {id:number;name:string;dsca:string|null;nmtp:number;nmpt:number;hits:number})[]>("SELECT id,name,dsca,nmtp,nmpt,hits FROM wbcat010 ORDER BY id"); return rows.map(r=>({id:+r.id,name:String(r.name),description:String(r.dsca??""),topicCount:+r.nmtp,postCount:+r.nmpt,views:+r.hits})); }
export async function findAdminArticle(id:number):Promise<AdminArticle|undefined>{await connection();const [rows]=await db.execute<(RowDataPacket & {id:number;title:string;intro:string|null;body:string|null;categoryId:number;imagePath:string|null;published:string;featured:string;sortFirst:string})[]>("SELECT id,name title,intro,body,arcat010_id categoryId,pimg imagePath,pubd published,fetd featured,awtp sortFirst FROM arart010 WHERE id=? LIMIT 1",[id]);const r=rows[0];return r?{id:+r.id,title:String(r.title),intro:String(r.intro??""),body:String(r.body??""),categoryId:+r.categoryId,imagePath:String(r.imagePath??""),published:r.published==="Yes",featured:r.featured==="Yes",sortFirst:r.sortFirst==="Yes"}:undefined}
export async function saveAdminArticle(input:{id?:number;title:string;intro:string;body:string;categoryId:number;imagePath?:string;published:boolean;featured:boolean;sortFirst:boolean;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();const fields=[input.title,input.intro,input.body,input.categoryId,input.published?"Yes":"No",input.featured?"Yes":"No",input.sortFirst?"Yes":"No",input.actorId,input.address.slice(0,16)];let id=input.id;if(id){const image=input.imagePath===undefined?null:input.imagePath;await c.execute("UPDATE arart010 SET name=?,intro=?,body=?,arcat010_id=?,pubd=?,fetd=?,awtp=?,lmby_tbl_users=?,ipad=?,lmdt=NOW()"+(image===null?"":" ,pimg=?")+" WHERE id=?",image===null?[...fields,id]:[...fields,image,id]);await writeLegacyAudit(c,{model:"Arart010",action:"Update",recordId:id,actorId:input.actorId,address:input.address,summary:`updated article ${input.title}`});}else{const [result]=await c.execute<ResultSetHeader>("INSERT INTO arart010 (name,intro,body,arcat010_id,pimg,pubd,fetd,awtp,crdt,lmdt,crby_tbl_users,lmby_tbl_users,ipad,hits,`like`) VALUES (?,?,?,?,?,?,?,?,NOW(),NOW(),?,?,?,0,0)",[input.title,input.intro,input.body,input.categoryId,input.imagePath??"",input.published?"Yes":"No",input.featured?"Yes":"No",input.sortFirst?"Yes":"No",input.actorId,input.actorId,input.address.slice(0,16)]);id=+result.insertId;await writeLegacyAudit(c,{model:"Arart010",action:"Insert",recordId:id,actorId:input.actorId,address:input.address,summary:`created article ${input.title}`});}await c.commit();return id!}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function saveCategory(input:{id?:number;name:string;description:string;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();let id=input.id;if(id){await c.execute("UPDATE arcat010 SET name=?,dsca=? WHERE id=?",[input.name,input.description,id]);await writeLegacyAudit(c,{model:"Arcat010",action:"Update",recordId:id,actorId:input.actorId,address:input.address,summary:`updated category ${input.name}`});}else{const [r]=await c.execute<ResultSetHeader>("INSERT INTO arcat010 (name,dsca,nmar) VALUES (?,?,0)",[input.name,input.description]);id=+r.insertId;await writeLegacyAudit(c,{model:"Arcat010",action:"Insert",recordId:id,actorId:input.actorId,address:input.address,summary:`created category ${input.name}`});}await c.commit();return id!}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function saveMenu(input:Omit<AdminMenu,"id">&{id?:number;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();const v=[input.parentId,input.title,input.position,input.tooltip,input.url,input.icon,input.visible?1:0,input.task,input.options];let id=input.id;if(id){await c.execute("UPDATE syadm001 SET parent_id=?,title=?,position=?,tooltip=?,url=?,icon=?,visible=?,task=?,options=? WHERE id=?",[...v,id]);await writeLegacyAudit(c,{model:"Syadm001",action:"Update",recordId:id,actorId:input.actorId,address:input.address,summary:`updated menu ${input.title}`});}else{const [r]=await c.execute<ResultSetHeader>("INSERT INTO syadm001 (parent_id,title,position,tooltip,url,icon,visible,task,options) VALUES (?,?,?,?,?,?,?,?,?)",v);id=+r.insertId;await writeLegacyAudit(c,{model:"Syadm001",action:"Insert",recordId:id,actorId:input.actorId,address:input.address,summary:`created menu ${input.title}`});}await c.commit();return id!}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function saveBoardCategory(input:{id?:number;name:string;description:string;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();let id=input.id;if(id){await c.execute("UPDATE wbcat010 SET name=?,dsca=? WHERE id=?",[input.name,input.description,id]);await writeLegacyAudit(c,{model:"Wbcat010",action:"Update",recordId:id,actorId:input.actorId,address:input.address,summary:`updated board category ${input.name}`});}else{const [r]=await c.execute<ResultSetHeader>("INSERT INTO wbcat010 (name,dsca,nmtp,nmpt,hits) VALUES (?,?,0,0,0)",[input.name,input.description]);id=+r.insertId;await writeLegacyAudit(c,{model:"Wbcat010",action:"Insert",recordId:id,actorId:input.actorId,address:input.address,summary:`created board category ${input.name}`});}await c.commit();return id!}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function saveTopic(input:{id?:number;title:string;body:string;categoryId:number;enabled:boolean;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();let id=input.id;if(id){await c.execute("UPDATE wbtpc010 SET name=?,dsca=?,wbcat010_id=?,enbl=?,lmby_tbl_users=?,ipad=?,lmdt=NOW() WHERE id=?",[input.title,input.body,input.categoryId,input.enabled?"Yes":"No",input.actorId,input.address.slice(0,16),id]);await writeLegacyAudit(c,{model:"Wbtpc010",action:"Update",recordId:id,actorId:input.actorId,address:input.address,summary:`updated topic ${input.title}`});}else{const [r]=await c.execute<ResultSetHeader>("INSERT INTO wbtpc010 (name,dsca,wbcat010_id,crdt,lmdt,crby_tbl_users,lmby_tbl_users,ipad,hits,nmmg,enbl) VALUES (?,?,?,NOW(),NOW(),?,?,?,0,0,?)",[input.title,input.body,input.categoryId,input.actorId,input.actorId,input.address.slice(0,16),input.enabled?"Yes":"No"]);id=+r.insertId;await writeLegacyAudit(c,{model:"Wbtpc010",action:"Insert",recordId:id,actorId:input.actorId,address:input.address,summary:`created topic ${input.title}`});}await c.commit();return id!}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function deleteAdminArticle(input:{id:number;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();await c.execute("DELETE FROM arart010 WHERE id=?",[input.id]);await writeLegacyAudit(c,{model:"Arart010",action:"Delete",recordId:input.id,actorId:input.actorId,address:input.address,summary:"deleted article"});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function deleteArticleCategory(input:{id:number;actorId:number;address:string}){if(input.id===1)throw new Error("NEWS_CATEGORY_PROTECTED");const c=await db.getConnection();try{await c.beginTransaction();const [rows]=await c.execute<RowDataPacket[]>("SELECT COUNT(*) total FROM arart010 WHERE arcat010_id=?",[input.id]);if(+rows[0]?.total)throw new Error("CATEGORY_IN_USE");await c.execute("DELETE FROM arcat010 WHERE id=?",[input.id]);await writeLegacyAudit(c,{model:"Arcat010",action:"Delete",recordId:input.id,actorId:input.actorId,address:input.address,summary:"deleted article category"});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function deleteSiteMenu(input:{id:number;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();const [rows]=await c.execute<RowDataPacket[]>("SELECT COUNT(*) total FROM syadm001 WHERE parent_id=?",[input.id]);if(+rows[0]?.total)throw new Error("MENU_HAS_CHILDREN");await c.execute("DELETE FROM syadm001 WHERE id=?",[input.id]);await writeLegacyAudit(c,{model:"Syadm001",action:"Delete",recordId:input.id,actorId:input.actorId,address:input.address,summary:"deleted menu"});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function deleteBoardCategory(input:{id:number;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();const [rows]=await c.execute<RowDataPacket[]>("SELECT COUNT(*) total FROM wbtpc010 WHERE wbcat010_id=?",[input.id]);if(+rows[0]?.total)throw new Error("BOARD_CATEGORY_IN_USE");await c.execute("DELETE FROM wbcat010 WHERE id=?",[input.id]);await writeLegacyAudit(c,{model:"Wbcat010",action:"Delete",recordId:input.id,actorId:input.actorId,address:input.address,summary:"deleted webboard category"});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function deleteBoardTopic(input:{id:number;actorId:number;address:string}){const c=await db.getConnection();try{await c.beginTransaction();await c.execute("DELETE FROM wbmsg010 WHERE wbtpc010_id=?",[input.id]);await c.execute("DELETE FROM wbtpc010 WHERE id=?",[input.id]);await writeLegacyAudit(c,{model:"Wbtpc010",action:"Delete",recordId:input.id,actorId:input.actorId,address:input.address,summary:"deleted topic and replies"});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
