import { connection } from "next/server";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { db } from "@/lib/db";
import { createLegacyMd5Password } from "@/lib/auth/legacy-password";
import { writeLegacyAudit } from "@/lib/admin-write";

export type AdminUser = { id: number; username: string; email: string | null; firstName: string; lastName: string; title: string; memberType: number; status: number; superuser: boolean; lastVisitAt: string };
type UserRow = RowDataPacket & { id: number; username: string; email: string | null; firstname: string | null; lastname: string | null; title: string | null; memtype: number | null; status: number; superuser: number; lastvisit_at: string };
const select = "SELECT u.id,u.username,u.email,p.firstname,p.lastname,p.title,p.memtype,u.status,u.superuser,u.lastvisit_at FROM tbl_users u LEFT JOIN tbl_profiles p ON p.user_id=u.id";
const map = (row: UserRow): AdminUser => ({ id:Number(row.id), username:String(row.username), email:row.email ? String(row.email):null, firstName:String(row.firstname ?? ""), lastName:String(row.lastname ?? ""), title:String(row.title ?? ""), memberType:Number(row.memtype ?? 0), status:Number(row.status), superuser:Number(row.superuser)===1, lastVisitAt:String(row.lastvisit_at) });
export async function listAdminUsers(keyword = ""): Promise<AdminUser[]> { await connection(); const values: string[]=[]; const where=keyword ? " WHERE u.username LIKE ? OR u.email LIKE ? OR p.firstname LIKE ? OR p.lastname LIKE ?" : ""; if(keyword) values.push(`%${keyword}%`,`%${keyword}%`,`%${keyword}%`,`%${keyword}%`); const [rows]=await db.execute<UserRow[]>(`${select}${where} ORDER BY u.id DESC LIMIT 200`,values); return rows.map(map); }
export async function findAdminUser(id:number): Promise<AdminUser|undefined> { await connection(); const [rows]=await db.execute<UserRow[]>(`${select} WHERE u.id=? LIMIT 1`,[id]); return rows[0] ? map(rows[0]):undefined; }
export async function createAdminUser(input:{username:string;password:string;email:string;firstName:string;lastName:string;title:string;memberType:number;status:number;superuser:boolean;actorId:number;address:string}):Promise<number>{const c=await db.getConnection();try{await c.beginTransaction();const [user]=await c.execute<ResultSetHeader>("INSERT INTO tbl_users (username,password,email,activkey,superuser,status) VALUES (?,?,?,?,?,?)",[input.username,createLegacyMd5Password(input.password),input.email||null,"",input.superuser?1:0,input.status]);const id=Number(user.insertId);await c.execute("INSERT INTO tbl_profiles (user_id,lastname,firstname,lang,sex,memtype,title,prcm,licn,uredu012_id) VALUES (?,?,?,'en',0,?,?,10,NULL,0)",[id,input.lastName,input.firstName,input.memberType,input.title]);await writeLegacyAudit(c,{model:"TblUsers",action:"Insert",recordId:id,actorId:input.actorId,address:input.address,summary:`created user ${input.username}`});await c.commit();return id}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function updateAdminUser(input:{id:number;username:string;email:string;firstName:string;lastName:string;title:string;memberType:number;status:number;superuser:boolean;actorId:number;address:string}):Promise<void>{const c=await db.getConnection();try{await c.beginTransaction();await c.execute("UPDATE tbl_users SET username=?,email=?,superuser=?,status=? WHERE id=?",[input.username,input.email||null,input.superuser?1:0,input.status,input.id]);await c.execute("UPDATE tbl_profiles SET lastname=?,firstname=?,memtype=?,title=? WHERE user_id=?",[input.lastName,input.firstName,input.memberType,input.title,input.id]);await writeLegacyAudit(c,{model:"TblUsers",action:"Update",recordId:input.id,actorId:input.actorId,address:input.address,summary:`updated user ${input.username}`});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function resetAdminUserPassword(input:{id:number;password:string;actorId:number;address:string}):Promise<void>{const c=await db.getConnection();try{await c.beginTransaction();await c.execute("UPDATE tbl_users SET password=?,activkey='' WHERE id=?",[createLegacyMd5Password(input.password),input.id]);await writeLegacyAudit(c,{model:"TblUsers",action:"Update",recordId:input.id,actorId:input.actorId,address:input.address,summary:"reset password"});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
export async function softDeleteAdminUser(input:{id:number;actorId:number;address:string}):Promise<void>{const c=await db.getConnection();try{await c.beginTransaction();await c.execute("UPDATE tbl_users SET status=-1 WHERE id=?",[input.id]);await writeLegacyAudit(c,{model:"TblUsers",action:"Delete",recordId:input.id,actorId:input.actorId,address:input.address,summary:"soft deleted user"});await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}
