import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Eye, MessageCircle } from "lucide-react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { formatThaiDate, redactPublicContactInfo, sanitizeLegacyHtml } from "@/lib/content-utils";
import { findPublicConsultationById } from "@/repositories/community-repository";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; if (!/^\d+$/u.test(id)) return {}; const topic = await findPublicConsultationById(Number(id)); return topic ? { title: topic.title, description: "คำถามและคำตอบสุขภาพตาจากกระดาน RCOPT", alternates: { canonical: `/community/questions/${topic.id}` }, robots: { index: false, follow: true } } : {}; }
export default async function ConsultationDetail({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; if (!/^\d+$/u.test(id)) notFound(); const topic = await findPublicConsultationById(Number(id)); if (!topic) notFound(); const safeBody = redactPublicContactInfo(sanitizeLegacyHtml(topic.body)); return <><SiteHeader /><main className="container-shell max-w-4xl py-12"><nav className="text-sm text-[var(--muted)]" aria-label="Breadcrumb"><Link href="/">หน้าหลัก</Link><span className="px-2">/</span><Link href="/community/questions">ปรึกษาจักษุแพทย์</Link><span className="px-2">/</span><span aria-current="page">หัวข้อสนทนา</span></nav><article className="card mt-7 p-6 sm:p-8"><p className="eyebrow">PUBLIC CONSULTATION</p><h1 className="mt-3 text-2xl font-extrabold leading-tight sm:text-4xl">{topic.title}</h1><div className="mt-5 flex flex-wrap gap-4 text-sm text-[var(--muted)]"><time dateTime={topic.createdAt}>{formatThaiDate(topic.createdAt)}</time><span className="inline-flex items-center gap-1"><MessageCircle size={15} /> {topic.replies.toLocaleString("th-TH")} คำตอบ</span><span className="inline-flex items-center gap-1"><Eye size={15} /> {topic.views.toLocaleString("th-TH")} อ่าน</span></div><div className="legacy-content mt-7 border-t border-[var(--border)] pt-7 text-[17px] leading-8" dangerouslySetInnerHTML={{ __html: safeBody }} /></article><section className="mt-8"><h2 className="section-title text-2xl">คำตอบ ({topic.repliesList.length.toLocaleString("th-TH")})</h2><div className="mt-4 grid gap-4">{topic.repliesList.map((reply) => <article key={reply.id} className="rounded-2xl border border-[var(--border)] bg-[#fffafb] p-5"><p className="text-xs text-[var(--muted)]">ผู้ร่วมสนทนา · <time dateTime={reply.createdAt}>{formatThaiDate(reply.createdAt)}</time></p><div className="legacy-content mt-3 leading-7" dangerouslySetInnerHTML={{ __html: redactPublicContactInfo(sanitizeLegacyHtml(reply.body)) }} /></article>)}</div>{!topic.repliesList.length && <p className="mt-4 rounded-2xl border border-[var(--border)] p-5 text-sm text-[var(--muted)]">ยังไม่มีคำตอบในหัวข้อนี้</p>}</section></main><SiteFooter /></>; }
