import { Image as ImageIcon, Link as LinkIcon } from "lucide-react";
import { LegacyImage } from "@/components/legacy-image";
import { env } from "@/lib/env";
import { listAdminBanners } from "@/repositories/admin-banner-repository";

export default async function AdminBannersPage() {
  const banners = await listAdminBanners();
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">BANNER MANAGEMENT</p><h1 className="mt-2 text-3xl font-extrabold">แบนเนอร์</h1><p className="mt-2 text-sm text-[var(--muted)]">ตรวจสอบข้อมูลจาก `cmban010` และการแสดงรูปจากระบบเดิม</p></div><span className={`rounded-full px-3 py-2 text-sm font-bold ${env.ADMIN_WRITE_ENABLED ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{env.ADMIN_WRITE_ENABLED ? "เปิดแก้ไขแล้ว" : "Read-only"}</span></div>
    <p className="mt-7 text-sm text-[var(--muted)]">ทั้งหมด {banners.length.toLocaleString("th-TH")} รายการ</p><div className="mt-3 grid gap-4 xl:grid-cols-2">{banners.map((banner) => <article key={banner.id} className="card overflow-hidden"><LegacyImage path={banner.imagePath} area="banner" alt={banner.title} className="h-44 w-full border-b border-[var(--border)] bg-[#fff9fb] p-3 object-contain" /><div className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-bold leading-6">{banner.title}</h2><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-bold ${banner.enabled ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-700"}`}>{banner.enabled ? "เปิดใช้" : "ปิดใช้"}</span></div><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-[var(--muted)]">{banner.description || "ไม่มีคำอธิบาย"}</p>{banner.href ? <a href={banner.href} target="_blank" rel="noreferrer" className="mt-4 inline-flex max-w-full items-center gap-2 text-sm font-bold text-[var(--primary-dark)]"><LinkIcon size={15} /><span className="truncate">{banner.href}</span></a> : <p className="mt-4 text-sm text-[var(--muted)]">ไม่มีลิงก์ปลายทาง</p>}</div></article>)}{!banners.length && <div className="card grid min-h-56 place-items-center gap-2 text-[var(--muted)] xl:col-span-2"><ImageIcon size={26} /><p>ยังไม่มีแบนเนอร์</p></div>}</div></>;
}
