import Link from "next/link";
import Image from "next/image";
import { ArrowRight, ChevronRight, HeartPulse, Search, ShieldCheck, Stethoscope } from "lucide-react";
import { SiteFooter } from "../components/site-footer";
import { SiteHeader } from "../components/site-header";
import { ContentCard } from "@/components/content-card";
import { LegacyImage } from "@/components/legacy-image";
import { getPublicBanners } from "@/repositories/banner-repository";
import { getHomepageContent, type PublicContent } from "@/repositories/content-repository";
import { getFeaturedVideos, type PublicVideo } from "@/repositories/video-repository";
import { VideoSection } from "@/components/video-section";

const cards = [{ icon: Stethoscope, title: "ค้นหาจักษุแพทย์", text: "ค้นหาจักษุแพทย์ตามชื่อ จังหวัด โรงพยาบาล และความเชี่ยวชาญ", href: "/doctors" }, { icon: HeartPulse, title: "ความรู้สุขภาพตา", text: "ข้อมูลสุขภาพตาที่อ่านง่ายและผ่านการเผยแพร่โดยผู้เชี่ยวชาญ", href: "/articles" }, { icon: ShieldCheck, title: "ข้อมูลสำหรับสมาชิก", text: "บริการและข่าวสารสำหรับสมาชิกของราชวิทยาลัยฯ", href: "/news" }];
export default async function Home() { let content: { news: PublicContent[]; articles: PublicContent[] } = { news: [], articles: [] }; let banners: Awaited<ReturnType<typeof getPublicBanners>> = []; let videos: PublicVideo[] = []; try { [content, banners, videos] = await Promise.all([getHomepageContent(), getPublicBanners(), getFeaturedVideos()]); } catch { /* Public page stays available if legacy content is temporarily unavailable. */ } return <><SiteHeader /><main>
  <section className="hero-banner relative overflow-hidden"><Image src="/brand/rcopt-hero-wave.png" alt="" fill priority sizes="100vw" className="object-cover" /><div className="container-shell relative z-10 grid min-h-[500px] items-center gap-8 py-16 lg:grid-cols-[1.1fr_.9fr] lg:py-20"><div><p className="eyebrow mb-5">ROYAL COLLEGE OF OPHTHALMOLOGISTS OF THAILAND</p><h1 className="max-w-xl text-4xl font-extrabold leading-[1.22] tracking-[-.04em] text-[#32272d] sm:text-6xl">ดูแลดวงตา<br /><span className="text-[var(--primary)]">ด้วยความรู้ที่เชื่อถือได้</span></h1><p className="mt-6 max-w-lg text-base leading-8 text-[var(--muted)] sm:text-lg">แหล่งรวมข้อมูลด้านจักษุวิทยา ข่าวสาร และบริการค้นหาจักษุแพทย์จากราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/doctors" className="button-primary gap-2">ค้นหาจักษุแพทย์ <ArrowRight size={17} /></Link><Link href="/about" className="button-outline">รู้จัก RCOPT</Link></div><div className="mt-10 flex items-center gap-3 text-sm text-[var(--muted)]"><span className="flex -space-x-2"><span className="h-8 w-8 rounded-full border-2 border-white bg-[#e8a4b9]" /><span className="h-8 w-8 rounded-full border-2 border-white bg-[#d67d9c]" /><span className="h-8 w-8 rounded-full border-2 border-white bg-[#b95178]" /></span><span>ข้อมูลโดยผู้เชี่ยวชาญด้านจักษุวิทยา</span></div></div><div className="hidden justify-items-center lg:grid">{banners[0] ? <LegacyImage path={banners[0].imagePath} area="banner" alt={banners[0].title} className="max-h-72 w-full max-w-md object-contain" /> : <Image src="/brand/rcopt-crest.png" alt="ตราราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย" width={180} height={242} className="h-auto w-40 object-contain drop-shadow-[0_16px_22px_rgba(126,78,96,.14)]" />}</div></div></section>
  <section className="relative z-10 -mt-12"><div className="container-shell card grid gap-4 p-5 md:grid-cols-[1fr_auto] md:items-center md:p-7"><div><p className="mb-1 text-sm font-bold text-[var(--ink)]">ค้นหาจักษุแพทย์ใกล้คุณ</p><p className="text-sm text-[var(--muted)]">ค้นหาข้อมูลแพทย์และโรงพยาบาลจากฐานข้อมูลเดิมของ RCOPT</p></div><Link href="/doctors" className="button-primary gap-2"><Search size={17} /> เริ่มค้นหา</Link></div></section>
  <section className="container-shell py-20"><div className="grid gap-5 md:grid-cols-3">{cards.map(({icon: Icon, title, text, href}) => <Link href={href} key={title} className="card group p-7"><span className="mb-6 inline-flex rounded-2xl bg-[var(--primary-light)] p-3 text-[var(--primary)]"><Icon size={23} /></span><h2 className="mb-3 text-lg font-extrabold">{title}</h2><p className="min-h-14 text-sm leading-7 text-[var(--muted)]">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[var(--primary-dark)]">ดูรายละเอียด <ChevronRight size={16} className="transition-transform group-hover:translate-x-1" /></span></Link>)}</div></section>
  <section className="bg-[var(--secondary)] py-20"><div className="container-shell"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="eyebrow mb-3">LATEST UPDATES</p><h2 className="section-title">ข่าวสารล่าสุด</h2></div><Link href="/news" className="hidden items-center gap-1 text-sm font-bold text-[var(--primary-dark)] sm:flex">ดูทั้งหมด <ArrowRight size={16} /></Link></div><div className="grid gap-5 md:grid-cols-3">{content.news.map((item) => <ContentCard key={item.id} item={item} kind="news" />)}</div>{!content.news.length && <p className="text-sm text-[var(--muted)]">ยังไม่พบข่าวที่เผยแพร่</p>}</div></section>
  <section className="container-shell py-20"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="eyebrow mb-3">KNOWLEDGE</p><h2 className="section-title">บทความและคลังความรู้ล่าสุด</h2></div><Link href="/articles" className="hidden items-center gap-1 text-sm font-bold text-[var(--primary-dark)] sm:flex">ดูทั้งหมด <ArrowRight size={16} /></Link></div><div className="grid gap-5 md:grid-cols-3">{content.articles.map((item) => <ContentCard key={item.id} item={item} kind="article" />)}</div>{!content.articles.length && <p className="text-sm text-[var(--muted)]">ยังไม่พบบทความที่เผยแพร่</p>}</section>
  <VideoSection videos={videos} />
  <section className="container-shell grid gap-12 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow mb-3">ABOUT RCOPT</p><h2 className="section-title mb-5">ร่วมสร้างสังคมที่มีสุขภาพตาที่ดี</h2><p className="leading-8 text-[var(--muted)]">ราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย มุ่งมั่นพัฒนามาตรฐานวิชาชีพ เผยแพร่ความรู้ และส่งเสริมการดูแลสุขภาพตาให้กับประชาชนอย่างต่อเนื่อง</p><Link href="/about" className="button-outline mt-7">เรียนรู้เพิ่มเติม</Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-[var(--primary-light)] p-7"><p className="text-4xl font-extrabold text-[var(--primary-dark)]">01</p><p className="mt-4 font-bold">มาตรฐานวิชาชีพ</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">ส่งเสริมมาตรฐานการรักษาและจริยธรรมทางการแพทย์</p></div><div className="rounded-3xl bg-[#f7f5f6] p-7 sm:mt-10"><p className="text-4xl font-extrabold text-[var(--primary-dark)]">02</p><p className="mt-4 font-bold">ความรู้เพื่อประชาชน</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">เผยแพร่ข้อมูลสุขภาพตาที่เข้าใจง่ายและเชื่อถือได้</p></div></div></section>
 </main><SiteFooter /></>; }
