import Link from "next/link";
import Image from "next/image";
import { ArrowRight, ChevronRight, HeartPulse, Search, ShieldCheck, Stethoscope } from "lucide-react";
import { SiteFooter } from "../components/site-footer";
import { SiteHeader } from "../components/site-header";
import { ContentCard } from "@/components/content-card";
import { getHomepageContent, type PublicContent } from "@/repositories/content-repository";
import { VideoSection } from "@/components/video-section";
import { SponsorSection } from "@/components/sponsor-section";

const cards = [{ icon: Stethoscope, title: "ค้นหาจักษุแพทย์", text: "ค้นหาจักษุแพทย์ตามชื่อ จังหวัด โรงพยาบาล และความเชี่ยวชาญ", href: "/doctors" }, { icon: HeartPulse, title: "ความรู้สุขภาพตา", text: "ข้อมูลสุขภาพตาที่อ่านง่ายและผ่านการเผยแพร่โดยผู้เชี่ยวชาญ", href: "/articles" }, { icon: ShieldCheck, title: "ข้อมูลสำหรับสมาชิก", text: "บริการและข่าวสารสำหรับสมาชิกของราชวิทยาลัยฯ", href: "/news" }];
export default async function Home() { let content: { news: PublicContent[]; articles: PublicContent[] } = { news: [], articles: [] }; try { content = await getHomepageContent(); } catch { /* Public page stays available if legacy content is temporarily unavailable. */ } return <><SiteHeader /><main>
  <section className="hero-banner relative isolate overflow-hidden"><Image src="/brand/rcopt-hero-wave.png" alt="" fill priority sizes="100vw" className="object-cover" /><div aria-hidden="true" className="absolute -right-24 top-12 -z-10 h-80 w-80 rounded-full border-[28px] border-white/50 sm:right-[7%]" /><div aria-hidden="true" className="absolute right-[14%] top-32 -z-10 h-28 w-28 rounded-full bg-[#f6c5d8]/45 blur-sm" /><div className="container-shell relative z-10 flex min-h-[500px] items-center py-16 sm:min-h-[540px] lg:py-20"><div className="max-w-3xl"><p className="eyebrow mb-5">ROYAL COLLEGE OF OPHTHALMOLOGISTS OF THAILAND</p><h1 className="max-w-2xl text-4xl font-extrabold leading-[1.2] tracking-[-.04em] text-[#32272d] sm:text-6xl">ดูแลดวงตา<br /><span className="text-[var(--primary)]">ด้วยความรู้ที่เชื่อถือได้</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-[var(--muted)] sm:text-lg">แหล่งรวมข้อมูลด้านจักษุวิทยา ข่าวสาร และบริการค้นหาจักษุแพทย์จากราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/doctors" className="button-primary gap-2">ค้นหาจักษุแพทย์ <ArrowRight size={17} /></Link><Link href="/about" className="button-outline bg-white/45 backdrop-blur-sm">รู้จัก RCOPT</Link></div><div className="mt-10 flex items-start gap-3 text-sm leading-6 text-[var(--muted)]"><span className="mt-0.5 flex shrink-0 -space-x-2" aria-hidden="true"><span className="h-8 w-8 rounded-full border-2 border-white bg-[#e8a4b9]" /><span className="h-8 w-8 rounded-full border-2 border-white bg-[#d67d9c]" /><span className="h-8 w-8 rounded-full border-2 border-white bg-[#b95178]" /></span><span className="max-w-xl">ดำเนินการตามที่ได้รับมอบหมายจากแพทยสภา ในการฝึกอบรมและสอบเพื่อเป็นผู้มีความรู้ความชำนาญในการประกอบวิชาชีพเวชกรรม สาขาจักษุวิทยา</span></div></div><div className="pointer-events-none absolute right-[2%] top-1/2 hidden w-[280px] -translate-y-1/2 lg:block xl:right-[5%] xl:w-[330px]"><div aria-hidden="true" className="absolute inset-[7%] rounded-full bg-white/75 blur-3xl" /><div className="relative rounded-[42%] border border-white/75 bg-white/30 p-5 shadow-[0_28px_60px_rgba(151,64,98,.18)] backdrop-blur-[2px]"><Image src="/brand/rcopt-crest.png" alt="ตราราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย" width={420} height={560} priority className="h-auto w-full drop-shadow-[0_18px_18px_rgba(85,45,19,.22)]" /></div></div></div></section>
  <section className="relative z-10 -mt-12"><div className="container-shell card grid gap-4 p-5 md:grid-cols-[1fr_auto] md:items-center md:p-7"><div><p className="mb-1 text-sm font-bold text-[var(--ink)]">ค้นหาจักษุแพทย์ใกล้คุณ</p><p className="text-sm text-[var(--muted)]">ค้นหาข้อมูลแพทย์และโรงพยาบาลจากฐานข้อมูลเดิมของ RCOPT</p></div><Link href="/doctors" className="button-primary gap-2"><Search size={17} /> เริ่มค้นหา</Link></div></section>
  <section className="container-shell py-20"><div className="grid gap-5 md:grid-cols-3">{cards.map(({icon: Icon, title, text, href}) => <Link href={href} key={title} className="card group p-7"><span className="mb-6 inline-flex rounded-2xl bg-[var(--primary-light)] p-3 text-[var(--primary)]"><Icon size={23} /></span><h2 className="mb-3 text-lg font-extrabold">{title}</h2><p className="min-h-14 text-sm leading-7 text-[var(--muted)]">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[var(--primary-dark)]">ดูรายละเอียด <ChevronRight size={16} className="transition-transform group-hover:translate-x-1" /></span></Link>)}</div></section>
  <section className="bg-[var(--secondary)] py-20"><div className="container-shell"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="eyebrow mb-3">LATEST UPDATES</p><h2 className="section-title">ข่าวสารล่าสุด</h2></div><Link href="/news" className="hidden items-center gap-1 text-sm font-bold text-[var(--primary-dark)] sm:flex">ดูทั้งหมด <ArrowRight size={16} /></Link></div><div className="grid gap-5 md:grid-cols-3">{content.news.map((item) => <ContentCard key={item.id} item={item} kind="news" />)}</div>{!content.news.length && <p className="text-sm text-[var(--muted)]">ยังไม่พบข่าวที่เผยแพร่</p>}</div></section>
  <section className="container-shell py-20"><div className="mb-9 flex items-end justify-between gap-4"><div><p className="eyebrow mb-3">KNOWLEDGE</p><h2 className="section-title">บทความและคลังความรู้ล่าสุด</h2></div><Link href="/articles" className="hidden items-center gap-1 text-sm font-bold text-[var(--primary-dark)] sm:flex">ดูทั้งหมด <ArrowRight size={16} /></Link></div><div className="grid gap-5 md:grid-cols-3">{content.articles.map((item) => <ContentCard key={item.id} item={item} kind="article" />)}</div>{!content.articles.length && <p className="text-sm text-[var(--muted)]">ยังไม่พบบทความที่เผยแพร่</p>}</section>
  <VideoSection />
  <SponsorSection />
  <section className="container-shell grid gap-12 py-20 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow mb-3">ABOUT RCOPT</p><h2 className="section-title mb-5">ร่วมสร้างสังคมที่มีสุขภาพตาที่ดี</h2><p className="leading-8 text-[var(--muted)]">ราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย มุ่งมั่นพัฒนามาตรฐานวิชาชีพ เผยแพร่ความรู้ และส่งเสริมการดูแลสุขภาพตาให้กับประชาชนอย่างต่อเนื่อง</p><Link href="/about" className="button-outline mt-7">เรียนรู้เพิ่มเติม</Link></div><div className="grid items-stretch gap-4 sm:grid-cols-2"><div className="h-full rounded-3xl bg-[var(--primary-light)] p-7"><p className="text-4xl font-extrabold text-[var(--primary-dark)]">01</p><p className="mt-4 font-bold">มาตรฐานวิชาชีพ</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">ส่งเสริมมาตรฐานการรักษาและจริยธรรมทางการแพทย์</p></div><div className="h-full rounded-3xl bg-[#f7f5f6] p-7"><p className="text-4xl font-extrabold text-[var(--primary-dark)]">02</p><p className="mt-4 font-bold">ความรู้เพื่อประชาชน</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">เผยแพร่ข้อมูลสุขภาพตาที่เข้าใจง่ายและเชื่อถือได้</p></div></div></section>
 </main><SiteFooter /></>; }
