"use client";

import Image from "next/image";
import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { BookOpen, BriefcaseBusiness, FileText, ImagePlus, Mail, Plus, Save, Share2, Trash2 } from "lucide-react";
import { removeProfileDetails, saveGallery, saveProfileDetails, type ProfileDetailsActionState } from "@/app/profile/details-actions";
import type { ProfileDetails } from "@/repositories/profile-details-repository";

const initialState: ProfileDetailsActionState = {};
const input = "mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-white px-3 text-sm outline-none focus:border-[var(--primary)] focus:ring-2 focus:ring-[var(--primary-light)]";
const textarea = "mt-1 min-h-24 w-full rounded-lg border border-[var(--border)] bg-white p-3 text-sm outline-none focus:border-[var(--primary)] focus:ring-2 focus:ring-[var(--primary-light)]";
const label = "block text-sm font-bold text-[var(--ink)]";
type Action = (state: ProfileDetailsActionState, formData: FormData) => Promise<ProfileDetailsActionState>;

function StateForm({ action, className = "", children }: { action: Action; className?: string; children: React.ReactNode }) {
  const [state, formAction, pending] = useActionState(action, initialState);
  const router = useRouter();
  useEffect(() => { if (state.success) router.refresh(); }, [router, state.success]);
  return <form action={formAction} className={className} encType={action === saveGallery ? "multipart/form-data" : undefined}>{children}{state.error && <p className="mt-3 rounded-lg bg-[#fff0f4] px-3 py-2 text-sm text-[#9b2f59]" role="alert">{state.error}</p>}{state.success && <p className="mt-3 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-800" role="status">{state.success}</p>}<button type="submit" disabled={pending} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[var(--primary)] px-4 py-2.5 text-sm font-bold text-white hover:bg-[var(--primary-dark)] disabled:opacity-60"><Save size={16} />{pending ? "กำลังบันทึก…" : "บันทึก"}</button></form>;
}

function DeleteButton({ section, itemId, targetUserId }: { section: "education" | "educationOverview" | "profession" | "academic" | "contact" | "social" | "gallery"; itemId: number; targetUserId?: number }) {
  const [state, action, pending] = useActionState(removeProfileDetails, initialState);
  const router = useRouter();
  useEffect(() => { if (state.success) router.refresh(); }, [router, state.success]);
  return <form action={action} className="mt-4"><input type="hidden" name="section" value={section} /><input type="hidden" name="itemId" value={itemId} />{targetUserId && <input type="hidden" name="targetUserId" value={targetUserId} />}<button type="submit" disabled={pending} className="inline-flex items-center gap-1.5 rounded-lg border border-rose-200 px-3 py-2 text-sm font-bold text-rose-700 hover:bg-rose-50 disabled:opacity-60"><Trash2 size={15} />ลบ</button>{state.error && <p className="mt-2 text-sm text-rose-700" role="alert">{state.error}</p>}</form>;
}

function Visibility({ values, selected }: { values: ProfileDetails["visibility"]; selected: number }) { return <label className={label}>การแสดงผล<select name="visibilityId" defaultValue={String(selected)} className={input}>{values.map((value) => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label>; }
function Meta({ section, itemId, targetUserId }: { section: "education" | "educationOverview" | "profession" | "academic" | "contact" | "social"; itemId?: number; targetUserId?: number }) { return <><input type="hidden" name="section" value={section} /><input type="hidden" name="itemId" value={itemId ?? ""} />{targetUserId && <input type="hidden" name="targetUserId" value={targetUserId} />}</>; }
function Block({ icon: Icon, title, description, children }: { icon: typeof BookOpen; title: string; description: string; children: React.ReactNode }) { return <section className="mt-8 border-t border-[var(--border)] pt-8"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[var(--primary-light)] text-[var(--primary)]"><Icon size={19} /></span><div><h2 className="text-xl font-extrabold">{title}</h2><p className="mt-1 text-sm text-[var(--muted)]">{description}</p></div></div><div className="mt-5 grid gap-4">{children}</div></section>; }
function Card({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-[var(--border)] bg-[#fffdfd] p-4 sm:p-5">{children}</div>; }

export function ProfileDetailsEditor({ details, targetUserId }: { details: ProfileDetails; targetUserId?: number }) {
  return <div className="mt-10">
    <div><p className="eyebrow">PROFESSIONAL PROFILE</p><h2 className="mt-2 text-2xl font-extrabold">ข้อมูลประกอบโปรไฟล์</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">เพิ่ม แก้ไข หรือลบข้อมูลการศึกษา วิชาชีพ วิชาการ ช่องทางติดต่อ social และรูปภาพได้จากหน้านี้</p></div>
    <Block icon={BookOpen} title="Education" description="ประวัติการศึกษาและคุณวุฒิ">
      {details.education.map((row) => <Card key={row.id}><StateForm action={saveProfileDetails}><Meta section="education" itemId={row.id} targetUserId={targetUserId} /><div className="grid gap-4 sm:grid-cols-2"><label className={label}>สถาบัน<input name="institution" required maxLength={255} defaultValue={row.institution} className={input} /></label><label className={label}>คุณวุฒิ<select name="educationTypeId" defaultValue={String(row.educationTypeId)} className={input}>{details.educationTypes.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label className={label}>หลักสูตร / สาขา<input name="subject" maxLength={255} defaultValue={row.subject} className={input} /></label><label className={label}>ปีที่สำเร็จ<input name="year" type="number" min="0" max="3000" defaultValue={row.year || ""} className={input} /></label><label className={label}>เกียรตินิยม<input name="honor" maxLength={100} defaultValue={row.honor} className={input} /></label><Visibility values={details.visibility} selected={row.visibilityId} /></div><label className={`${label} mt-4`}>รายละเอียด<textarea name="details" maxLength={4000} defaultValue={row.details} className={textarea} /></label></StateForm><DeleteButton section="education" itemId={row.id} targetUserId={targetUserId} /></Card>)}
      <Card><p className="mb-4 flex items-center gap-2 font-bold"><Plus size={17} className="text-[var(--primary)]" />เพิ่มประวัติการศึกษา</p><StateForm action={saveProfileDetails}><Meta section="education" targetUserId={targetUserId} /><div className="grid gap-4 sm:grid-cols-2"><label className={label}>สถาบัน<input name="institution" required maxLength={255} className={input} /></label><label className={label}>คุณวุฒิ<select name="educationTypeId" required defaultValue="" className={input}><option value="" disabled>เลือกคุณวุฒิ</option>{details.educationTypes.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label className={label}>หลักสูตร / สาขา<input name="subject" maxLength={255} className={input} /></label><label className={label}>ปีที่สำเร็จ<input name="year" type="number" min="0" max="3000" className={input} /></label><label className={label}>เกียรตินิยม<input name="honor" maxLength={100} className={input} /></label><Visibility values={details.visibility} selected={1} /></div><label className={`${label} mt-4`}>รายละเอียด<textarea name="details" maxLength={4000} className={textarea} /></label></StateForm></Card>
      <TextBlock title="ข้อมูลเพิ่มเติมด้านการศึกษา" description="ข้อมูล Education เพิ่มเติมตามหน้าโปรไฟล์เดิม" icon={BookOpen} section="educationOverview" rows={details.educationOverview} visibility={details.visibility} targetUserId={targetUserId} />
    </Block>
    <TextBlock title="Profession" description="ประวัติและความเชี่ยวชาญด้านวิชาชีพ" icon={BriefcaseBusiness} section="profession" rows={details.profession} visibility={details.visibility} targetUserId={targetUserId} />
    <TextBlock title="Academic" description="ผลงาน บทบาท หรือประวัติด้านวิชาการ" icon={FileText} section="academic" rows={details.academic} visibility={details.visibility} targetUserId={targetUserId} />
    <Block icon={Mail} title="Contact" description="ข้อมูลติดต่อและที่อยู่">
      {details.contacts.map((row) => <ContactForm key={row.id} row={row} details={details} targetUserId={targetUserId} />)}
      <ContactForm details={details} targetUserId={targetUserId} />
    </Block>
    <Block icon={Share2} title="Social" description="ลิงก์ช่องทาง social และเว็บไซต์">
      {details.social.map((row) => <SocialForm key={row.id} row={row} details={details} targetUserId={targetUserId} />)}
      <SocialForm details={details} targetUserId={targetUserId} />
    </Block>
    <Block icon={ImagePlus} title="Gallery" description="รูปภาพไม่เกิน 3 MB รองรับ JPG, PNG, GIF และ WebP">
      {details.gallery.map((row) => <Card key={row.id}><div className="grid gap-5 sm:grid-cols-[144px_1fr]"><Image src={row.imageUrl} alt={row.name || "รูปในแกลเลอรี"} width={144} height={108} unoptimized className="h-28 w-36 rounded-xl border border-[var(--border)] object-cover" /><StateForm action={saveGallery}><input type="hidden" name="itemId" value={row.id} />{targetUserId && <input type="hidden" name="targetUserId" value={targetUserId} />}<div className="grid gap-4 sm:grid-cols-2"><label className={label}>ชื่อภาพ<input name="name" required maxLength={45} defaultValue={row.name} className={input} /></label><Visibility values={details.visibility} selected={row.visibilityId} /></div><label className={`${label} mt-4`}>คำอธิบาย<textarea name="details" maxLength={4000} defaultValue={row.details} className={textarea} /></label><label className={`${label} mt-4`}>เปลี่ยนรูปภาพ (ไม่บังคับ)<input name="image" type="file" accept="image/jpeg,image/png,image/gif,image/webp" className="mt-1 block w-full text-sm" /></label><label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="isProfilePicture" value="yes" defaultChecked={row.isProfilePicture} className="h-4 w-4 accent-[var(--primary)]" />ใช้เป็นรูปโปรไฟล์</label><input type="hidden" name="isProfilePicture" value="no" /></StateForm></div><DeleteButton section="gallery" itemId={row.id} targetUserId={targetUserId} /></Card>)}
      <Card><p className="mb-4 flex items-center gap-2 font-bold"><Plus size={17} className="text-[var(--primary)]" />เพิ่มรูปภาพ</p><StateForm action={saveGallery}><input type="hidden" name="itemId" value="" />{targetUserId && <input type="hidden" name="targetUserId" value={targetUserId} />}<div className="grid gap-4 sm:grid-cols-2"><label className={label}>ชื่อภาพ<input name="name" required maxLength={45} className={input} /></label><Visibility values={details.visibility} selected={1} /></div><label className={`${label} mt-4`}>คำอธิบาย<textarea name="details" maxLength={4000} className={textarea} /></label><label className={`${label} mt-4`}>เลือกไฟล์รูปภาพ<input name="image" required type="file" accept="image/jpeg,image/png,image/gif,image/webp" className="mt-1 block w-full text-sm" /></label><label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="isProfilePicture" value="yes" className="h-4 w-4 accent-[var(--primary)]" />ใช้เป็นรูปโปรไฟล์</label><input type="hidden" name="isProfilePicture" value="no" /></StateForm></Card>
    </Block>
  </div>;
}

function TextBlock({ title, description, icon, section, rows, visibility, targetUserId }: { title: string; description: string; icon: typeof BookOpen; section: "educationOverview" | "profession" | "academic"; rows: ProfileDetails["profession"]; visibility: ProfileDetails["visibility"]; targetUserId?: number }) { return <Block icon={icon} title={title} description={description}>{rows.map((row) => <Card key={row.id}><StateForm action={saveProfileDetails}><Meta section={section} itemId={row.id} targetUserId={targetUserId} /><label className={label}>รายละเอียด<textarea name="details" required maxLength={4000} defaultValue={row.details} className={textarea} /></label><div className="mt-4 max-w-xs"><Visibility values={visibility} selected={row.visibilityId} /></div></StateForm><DeleteButton section={section} itemId={row.id} targetUserId={targetUserId} /></Card>)}<Card><p className="mb-4 flex items-center gap-2 font-bold"><Plus size={17} className="text-[var(--primary)]" />เพิ่มรายการ</p><StateForm action={saveProfileDetails}><Meta section={section} targetUserId={targetUserId} /><label className={label}>รายละเอียด<textarea name="details" required maxLength={4000} className={textarea} /></label><div className="mt-4 max-w-xs"><Visibility values={visibility} selected={1} /></div></StateForm></Card></Block>; }

function ContactForm({ row, details, targetUserId }: { row?: ProfileDetails["contacts"][number]; details: ProfileDetails; targetUserId?: number }) { return <Card><p className="mb-4 flex items-center gap-2 font-bold">{row ? "แก้ไขช่องทางติดต่อ" : <><Plus size={17} className="text-[var(--primary)]" />เพิ่มช่องทางติดต่อ</>}</p><StateForm action={saveProfileDetails}><Meta section="contact" itemId={row?.id} targetUserId={targetUserId} /><div className="grid gap-4 sm:grid-cols-2"><label className={label}>ชื่อรายการ<input name="name" required maxLength={100} defaultValue={row?.name} className={input} /></label><label className={label}>ประเภท<select name="contactTypeId" required defaultValue={row ? String(row.contactTypeId) : ""} className={input}><option value="" disabled>เลือกประเภท</option>{details.contactTypes.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label className={label}>โทรศัพท์<input name="telephone" maxLength={45} defaultValue={row?.telephone} className={input} /></label><label className={label}>มือถือ<input name="mobile" maxLength={45} defaultValue={row?.mobile} className={input} /></label><label className={label}>อีเมล<input name="email" type="email" maxLength={45} defaultValue={row?.email} className={input} /></label><label className={label}>รหัสไปรษณีย์<input name="postcode" maxLength={5} defaultValue={row?.postcode} className={input} /></label><label className={label}>จังหวัด (รหัสเดิม)<input name="provinceId" type="number" min="0" defaultValue={row?.provinceId || 0} className={input} /></label><label className={label}>อำเภอ/เขต (รหัสเดิม)<input name="districtId" type="number" min="0" defaultValue={row?.districtId || 0} className={input} /></label><label className={label}>เว็บไซต์<input name="url" type="url" maxLength={255} defaultValue={row?.url} className={input} /></label><label className={label}>ลิงก์แผนที่<input name="mapUrl" type="url" maxLength={255} defaultValue={row?.mapUrl} className={input} /></label><label className={label}>พิกัด / short URL<input name="gps" maxLength={45} defaultValue={row?.gps} className={input} /></label><Visibility values={details.visibility} selected={row?.visibilityId ?? 1} /></div><label className={`${label} mt-4`}>ที่อยู่<textarea name="address" maxLength={255} defaultValue={row?.address} className={textarea} /></label><label className={`${label} mt-4`}>รายละเอียด<textarea name="details" maxLength={4000} defaultValue={row?.details} className={textarea} /></label></StateForm>{row && <DeleteButton section="contact" itemId={row.id} targetUserId={targetUserId} />}</Card>; }

function SocialForm({ row, details, targetUserId }: { row?: ProfileDetails["social"][number]; details: ProfileDetails; targetUserId?: number }) { return <Card><p className="mb-4 flex items-center gap-2 font-bold">{row ? "แก้ไข social" : <><Plus size={17} className="text-[var(--primary)]" />เพิ่ม social</>}</p><StateForm action={saveProfileDetails}><Meta section="social" itemId={row?.id} targetUserId={targetUserId} /><div className="grid gap-4 sm:grid-cols-2"><label className={label}>ประเภท<select name="socialTypeId" required defaultValue={row ? String(row.socialTypeId) : ""} className={input}><option value="" disabled>เลือกประเภท</option>{details.socialTypes.map((value) => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label className={label}>ชื่อที่แสดง<input name="name" required maxLength={4000} defaultValue={row?.name} className={input} /></label><label className={label}>ระบุประเภทอื่น<input name="customSocial" maxLength={100} defaultValue={row?.customSocial} className={input} /></label><Visibility values={details.visibility} selected={row?.visibilityId ?? 1} /></div><label className={`${label} mt-4`}>ลิงก์<input name="url" type="url" required maxLength={4000} defaultValue={row?.url} className={input} /></label></StateForm>{row && <DeleteButton section="social" itemId={row.id} targetUserId={targetUserId} />}</Card>; }
