/* eslint-disable @next/next/no-img-element */
import { Play, Youtube } from "lucide-react";
import { stripLegacyHtml } from "@/lib/content-utils";
import type { PublicVideo } from "@/repositories/video-repository";

const legacyHomepageVideo = { youtubeId: "CWYCnIq6-ss", title: "วีดิทัศน์แนะนำจากราชวิทยาลัยฯ", description: "ความรู้และกิจกรรมจากราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย" };

export function VideoSection({ videos }: { videos: PublicVideo[] }) {
  const related = videos.filter((video) => video.youtubeId !== legacyHomepageVideo.youtubeId).slice(0, 3);
  return <section className="bg-[#3a202d] py-20 text-white"><div className="container-shell"><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow !text-[#f4a6c3]">RCOPT VIDEO</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">วิดีโอความรู้เกี่ยวกับดวงตา</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#f3dce5]">ชมความรู้และกิจกรรมจากช่อง YouTube ของราชวิทยาลัยจักษุแพทย์แห่งประเทศไทย</p></div><a href={`https://www.youtube.com/watch?v=${legacyHomepageVideo.youtubeId}`} target="_blank" rel="noopener noreferrer" className="button-outline border-[#f2a7c4] text-white hover:bg-white/10">ดูบน YouTube <Youtube className="ml-2" size={17} /></a></div><div className="grid gap-6 lg:grid-cols-[1.45fr_.85fr]"><article className="overflow-hidden rounded-[22px] border border-white/15 bg-black/20"><div className="aspect-video"><iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${legacyHomepageVideo.youtubeId}`} title={legacyHomepageVideo.title} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="p-5"><h3 className="font-bold">{legacyHomepageVideo.title}</h3><p className="mt-2 text-sm leading-6 text-[#f3dce5]">{legacyHomepageVideo.description}</p></div></article><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{related.map((video) => <a key={video.id} href={`https://www.youtube.com/watch?v=${video.youtubeId}`} target="_blank" rel="noopener noreferrer" className="group flex gap-4 rounded-2xl border border-white/15 bg-white/5 p-3 hover:bg-white/10"><div className="relative aspect-video w-36 shrink-0 overflow-hidden rounded-xl bg-[#5b3444]"><img src={`https://i.ytimg.com/vi/${video.youtubeId}/hqdefault.jpg`} alt="" className="h-full w-full object-cover" loading="lazy" /><span className="absolute inset-0 grid place-items-center bg-black/20"><span className="grid h-10 w-10 place-items-center rounded-full bg-[var(--primary)] text-white shadow-lg"><Play size={18} fill="currentColor" /></span></span></div><div className="min-w-0 py-1"><h3 className="line-clamp-2 font-bold leading-6">{video.title}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 text-[#f3dce5]">{stripLegacyHtml(video.description) || "รับชมวิดีโอ"}</p></div></a>)}</div></div></div></section>;
}
