/* eslint-disable @next/next/no-img-element */
import { Play, Video } from "lucide-react";
import { legacyHomepageVideos, type HomepageVideo } from "@/lib/legacy-homepage-content";

function VideoCard({ video }: { video: HomepageVideo }) {
  return <a href={`https://www.youtube.com/watch?v=${video.youtubeId}`} target="_blank" rel="noopener noreferrer" className="group overflow-hidden rounded-2xl border border-white/15 bg-white/5 hover:bg-white/10"><div className="relative aspect-video bg-[#5b3444]"><img src={`https://i.ytimg.com/vi/${video.youtubeId}/hqdefault.jpg`} alt="" className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]" loading="lazy" /><span className="absolute inset-0 grid place-items-center bg-black/25"><span className="grid h-11 w-11 place-items-center rounded-full bg-[var(--primary)] text-white shadow-lg transition group-hover:scale-110"><Play size={19} fill="currentColor" /></span></span></div><div className="p-4"><h3 className="line-clamp-2 font-bold leading-6">{video.title}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 text-[#f3dce5]">{video.description}</p></div></a>;
}

export function VideoSection() {
  const [featuredVideo, ...remainingVideos] = legacyHomepageVideos;
  return <section className="bg-[#3a202d] py-16 text-white sm:py-20"><div className="container-shell"><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow !text-[#f4a6c3]">RCOPT VIDEO</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">วิดีโอความรู้เกี่ยวกับดวงตา</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#f3dce5]">รวบรวมวิดีโอ YouTube ทั้งหมดจากหน้าแรกของเว็บไซต์เดิม เพื่อให้รับชมได้สะดวกยิ่งขึ้น</p></div><a href={`https://www.youtube.com/watch?v=${featuredVideo.youtubeId}`} target="_blank" rel="noopener noreferrer" className="button-outline border-[#f2a7c4] text-white hover:bg-white/10">ดูบน YouTube <Video className="ml-2" size={17} /></a></div><div className="grid gap-6 lg:grid-cols-[1.35fr_.85fr]"><article className="overflow-hidden rounded-[22px] border border-white/15 bg-black/20"><div className="aspect-video"><iframe className="h-full w-full" src={`https://www.youtube-nocookie.com/embed/${featuredVideo.youtubeId}`} title={featuredVideo.title} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="p-5"><h3 className="font-bold">{featuredVideo.title}</h3><p className="mt-2 text-sm leading-6 text-[#f3dce5]">{featuredVideo.description}</p></div></article><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{remainingVideos.slice(0, 2).map((video) => <VideoCard key={video.youtubeId} video={video} />)}</div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{remainingVideos.slice(2).map((video) => <VideoCard key={video.youtubeId} video={video} />)}</div></div></section>;
}
