import Link from "next/link";
import { Search, UserRound } from "lucide-react";
import { listAdminUsers } from "@/repositories/admin-user-repository";

function pageNumber(value: string | undefined) { return value && /^\d+$/u.test(value) ? Math.min(Math.max(Number(value), 1), 10_000) : 1; }

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const { q = "", page: rawPage } = await searchParams;
  const keyword = q.trim().slice(0, 100);
  const page = pageNumber(rawPage);
  const result = await listAdminUsers({ keyword: keyword || undefined, page });
  const totalPages = Math.max(1, Math.ceil(result.total / 25));
  const pageStart = Math.max(1, page - 2);
  const pageEnd = Math.min(totalPages, pageStart + 4);
  return <><div><p className="eyebrow">USER MANAGEMENT</p><h1 className="mt-2 text-3xl font-extrabold">ผู้ใช้และข้อมูลประกอบโปรไฟล์</h1><p className="mt-2 text-sm text-[var(--muted)]">ค้นหาและแก้ไขข้อมูล Education, Profession, Academic, Contact, Social และ Gallery ของสมาชิก</p></div><form className="mt-6 flex max-w-xl gap-2"><label className="sr-only" htmlFor="user-search">ค้นหาผู้ใช้</label><input id="user-search" name="q" defaultValue={keyword} placeholder="ชื่อผู้ใช้ อีเมล หรือชื่อ-นามสกุล" className="h-11 min-w-0 flex-1 rounded-xl border border-[var(--border)] bg-white px-4 outline-none focus:border-[var(--primary)]" /><button className="inline-flex items-center gap-2 rounded-xl bg-[var(--primary)] px-4 text-sm font-bold text-white"><Search size={16} />ค้นหา</button></form><p className="mt-6 text-sm text-[var(--muted)]">พบ {result.total.toLocaleString("th-TH")} รายการ · หน้า {Math.min(page, totalPages)} / {totalPages}</p><div className="mt-3 overflow-hidden rounded-2xl border border-[var(--border)] bg-white"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-[#fff6f8] text-[var(--muted)]"><tr><th className="px-5 py-3 font-bold">ผู้ใช้</th><th className="px-5 py-3 font-bold">ประเภท</th><th className="px-5 py-3 font-bold">สถานะ</th><th className="px-5 py-3"><span className="sr-only">จัดการ</span></th></tr></thead><tbody>{result.rows.map((user) => <tr key={user.id} className="border-t border-[var(--border)]"><td className="px-5 py-4"><div className="font-bold">{[user.title, user.firstName, user.lastName].filter(Boolean).join(" ") || user.username}</div><div className="mt-1 text-xs text-[var(--muted)]">{user.username}{user.email ? ` · ${user.email}` : ""}</div></td><td className="px-5 py-4">{user.memberType === 2 ? "จักษุแพทย์" : "สมาชิก"}</td><td className="px-5 py-4"><span className={user.status === 1 ? "font-bold text-emerald-700" : "font-bold text-rose-700"}>{user.status === 1 ? "ใช้งาน" : "ไม่ใช้งาน"}</span></td><td className="px-5 py-4 text-right"><Link href={`/admin/users/${user.id}`} className="inline-flex items-center gap-2 rounded-lg border border-[var(--border)] px-3 py-2 font-bold text-[var(--primary-dark)] hover:bg-[var(--primary-light)]"><UserRound size={16} />จัดการ</Link></td></tr>)}</tbody></table></div>{!result.rows.length && <p className="p-6 text-sm text-[var(--muted)]">ไม่พบผู้ใช้</p>}</div>{totalPages > 1 && <nav className="mt-7 flex flex-wrap justify-center gap-2" aria-label="เปลี่ยนหน้าผู้ใช้">{Array.from({ length: pageEnd - pageStart + 1 }, (_, index) => pageStart + index).map((value) => { const params = new URLSearchParams(); if (keyword) params.set("q", keyword); params.set("page", String(value)); return <Link key={value} href={`/admin/users?${params.toString()}`} className={`rounded-lg border px-3 py-2 text-sm ${value === page ? "border-[var(--primary)] bg-[var(--primary)] text-white" : "border-[var(--border)] bg-white"}`}>{value}</Link>; })}</nav>}</>;
}
