import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteFooter } from "../../../components/site-footer";
import { SiteHeader } from "../../../components/site-header";
import { findDoctorById } from "../../../repositories/doctor-repository";
import { LegacyImage } from "@/components/legacy-image";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; if (!/^\d+$/u.test(id)) return {}; const doctor = await findDoctorById(Number(id)); return doctor ? { title: `${doctor.title ?? ""} ${doctor.firstname} ${doctor.lastname}`.trim(), description: "ข้อมูลจักษุแพทย์ที่เผยแพร่ต่อสาธารณะโดย RCOPT", alternates: { canonical: `/doctors/${doctor.user_id}` } } : {}; }

export default async function DoctorDetail({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; if (!/^\d+$/u.test(id)) notFound(); let doctor; try { doctor = await findDoctorById(Number(id)); } catch { doctor = undefined; } if (!doctor) notFound(); const fullName = `${doctor.title ?? ""} ${doctor.firstname} ${doctor.lastname}`.trim(); const structuredDoctor = { "@context": "https://schema.org", "@type": "Physician", name: fullName, medicalSpecialty: doctor.specialties, worksFor: doctor.workplaces.map((workplace) => ({ "@type": "Hospital", name: workplace.name, address: workplace.province || undefined })) }; return <><SiteHeader /><main className="container-shell min-h-[58vh] py-12"><nav className="text-sm text-[var(--muted)]" aria-label="Breadcrumb"><Link href="/">หน้าหลัก</Link><span className="px-2">/</span><Link href="/doctors">ค้นหาจักษุแพทย์</Link><span className="px-2">/</span><span aria-current="page">{doctor.firstname}</span></nav><p className="eyebrow mb-3 mt-7">DOCTOR PROFILE</p><h1 className="section-title">{fullName}</h1><div className="card mt-8 grid max-w-3xl gap-7 p-7 sm:grid-cols-[110px_1fr]"><LegacyImage path={doctor.photoPath || "doctor.png"} area="member" alt={`รูป ${fullName}`} className="h-28 w-28 rounded-2xl border border-[var(--border)] object-cover" /><div><p className="text-sm text-[var(--muted)]">ข้อมูลสมาชิกที่เปิดเผยต่อสาธารณะ</p><dl className="mt-5 grid gap-6 text-sm sm:grid-cols-2"><div><dt className="text-[var(--muted)]">ชื่อ-นามสกุล</dt><dd className="mt-1 font-bold">{fullName}</dd></div><div><dt className="text-[var(--muted)]">เลขใบอนุญาต</dt><dd className="mt-1 font-bold">{doctor.licn ?? "ไม่ระบุ"}</dd></div><div className="sm:col-span-2"><dt className="text-[var(--muted)]">สาขาความเชี่ยวชาญ</dt><dd className="mt-1 font-bold">{doctor.specialties.length ? doctor.specialties.join(", ") : "ไม่ระบุ"}</dd></div><div className="sm:col-span-2"><dt className="text-[var(--muted)]">สถานที่ทำงาน</dt><dd className="mt-1 grid gap-1 font-bold">{doctor.workplaces.length ? doctor.workplaces.map((workplace, index) => <span key={`${workplace.name}-${index}`}>{workplace.name}{workplace.province ? ` — ${workplace.province}` : ""}</span>) : "ไม่ระบุ"}</dd></div></dl></div></div></main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredDoctor) }} /><SiteFooter /></>; }
