import Link from "next/link";
import { FolderPlus, GitBranch, GripVertical } from "lucide-react";
import { deleteMenu, saveSiteMenu } from "@/app/admin/(protected)/content-actions";
import { type AdminMenu, listAdminMenuTree } from "@/repositories/admin-cms-repository";

const input = "mt-1 h-10 w-full rounded-lg border border-[var(--border)] bg-white px-3 text-sm outline-none focus:border-[var(--primary)]";
function pageNumber(value: string | undefined) { return value && /^\d+$/u.test(value) ? Math.max(1, Math.min(Number(value), 10_000)) : 1; }

function ParentSelect({ roots, selected, selfId }: { roots: Array<Pick<AdminMenu, "id" | "title">>; selected: number; selfId?: number }) {
  return <label>อยู่ใต้เมนู<select name="parentId" defaultValue={selected} className={input}><option value="0">เมนูหลัก</option>{roots.filter((item) => item.id !== selfId).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>;
}

function MenuFields({ roots, item }: { roots: Array<Pick<AdminMenu, "id" | "title">>; item?: AdminMenu }) {
  return <><label>ชื่อเมนู<input name="title" required maxLength={35} defaultValue={item?.title ?? ""} className={input} /></label><label>URL<input name="url" maxLength={255} defaultValue={item?.url ?? ""} className={input} /></label><ParentSelect roots={roots} selected={item?.parentId ?? 0} selfId={item?.id} /><label>ลำดับ<input name="position" type="number" min="0" defaultValue={item?.position ?? 0} className={input} /></label><label>Tooltip<input name="tooltip" maxLength={100} defaultValue={item?.tooltip ?? ""} className={input} /></label><label>Icon<input name="icon" maxLength={50} defaultValue={item?.icon ?? ""} className={input} /></label><label>Task<input name="task" maxLength={64} defaultValue={item?.task ?? ""} className={input} /></label><label>Options<input name="options" maxLength={100} defaultValue={item?.options ?? ""} className={input} /></label><label className="flex items-end gap-2 pb-2"><input name="visible" type="checkbox" value="yes" defaultChecked={item?.visible ?? true} />แสดงเมนู</label></>;
}

function MenuEditor({ item, roots }: { item: AdminMenu; roots: Array<Pick<AdminMenu, "id" | "title">> }) {
  return <details className={`rounded-xl border p-4 ${item.parentId ? "border-[#f2d9e2] bg-[#fffafd]" : "border-[var(--border)] bg-white"}`}><summary className="flex cursor-pointer items-center gap-2 font-bold"><GripVertical size={16} className="text-[var(--primary)]" />{item.title}<span className="ml-1 text-xs font-normal text-[var(--muted)]">#{item.id} · {item.visible ? "แสดง" : "ซ่อน"}</span></summary><form action={saveSiteMenu} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><input type="hidden" name="id" value={item.id} /><MenuFields roots={roots} item={item} /><div className="flex gap-3"><button className="button-outline">บันทึก</button><button formAction={deleteMenu} className="text-sm font-bold text-rose-700">ลบ</button></div></form></details>;
}

function NewChildMenu({ root, roots }: { root: AdminMenu; roots: Array<Pick<AdminMenu, "id" | "title">> }) {
  void roots;
  return <details className="ml-5 mt-3 border-l-2 border-[var(--primary-light)] pl-4"><summary className="inline-flex cursor-pointer items-center gap-2 text-sm font-bold text-[var(--primary-dark)]"><FolderPlus size={16} />เพิ่มเมนูย่อยใต้ “{root.title}”</summary><form action={saveSiteMenu} className="mt-4 grid gap-3 rounded-xl bg-[#fff8fb] p-4 md:grid-cols-2 xl:grid-cols-3"><label>ชื่อเมนู<input name="title" required maxLength={35} className={input} /></label><label>URL<input name="url" maxLength={255} className={input} /></label><input type="hidden" name="parentId" value={root.id} /><p className="self-end pb-2 text-sm text-[var(--muted)]">เมนูหลัก: {root.title}</p><label>ลำดับ<input name="position" type="number" min="0" defaultValue="0" className={input} /></label><label>Tooltip<input name="tooltip" maxLength={100} className={input} /></label><label>Icon<input name="icon" maxLength={50} className={input} /></label><label>Task<input name="task" maxLength={64} className={input} /></label><label>Options<input name="options" maxLength={100} className={input} /></label><label className="flex items-end gap-2 pb-2"><input name="visible" type="checkbox" value="yes" defaultChecked />แสดงเมนู</label><button className="button-primary">เพิ่มเมนูย่อย</button></form></details>;
}

export default async function AdminMenuPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const currentPage = pageNumber((await searchParams).page);
  const result = await listAdminMenuTree({ page: currentPage });
  const roots = result.rows.filter((item) => item.parentId === 0);
  const orphans = result.rows.filter((item) => item.parentId !== 0 && !roots.some((root) => root.id === item.parentId));
  const totalPages = Math.max(1, Math.ceil(result.total / 10));
  return <><p className="eyebrow">SITE CONFIGURATION</p><h1 className="mt-2 text-3xl font-extrabold">เมนูเว็บไซต์</h1><p className="mt-2 text-sm text-[var(--muted)]">จัดกลุ่มเมนูย่อยใต้เมนูหลักได้โดยเลือก “อยู่ใต้เมนู” หรือกดเพิ่มเมนูย่อยใต้เมนูหลักโดยตรง</p><details className="card mt-7 p-5"><summary className="cursor-pointer font-bold">เพิ่มเมนูหลักใหม่</summary><form action={saveSiteMenu} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><MenuFields roots={roots} /><button className="button-primary">เพิ่มเมนู</button></form></details><div className="mt-6 space-y-5">{roots.map((root) => <section key={root.id} className="card p-5"><div className="flex items-center gap-2"><GitBranch size={18} className="text-[var(--primary)]" /><h2 className="font-extrabold">เมนูหลัก</h2></div><div className="mt-3"><MenuEditor item={root} roots={roots} /></div><div className="mt-3 space-y-3">{result.rows.filter((item) => item.parentId === root.id).map((child) => <div key={child.id} className="ml-5 border-l-2 border-[#f2d9e2] pl-4"><p className="mb-2 text-xs font-bold text-[var(--muted)]">เมนูย่อย</p><MenuEditor item={child} roots={roots} /></div>)}</div><NewChildMenu root={root} roots={roots} /></section>)}{orphans.length > 0 && <section className="card border-amber-200 p-5"><h2 className="font-extrabold text-amber-900">เมนูที่ยังไม่พบเมนูหลักในหน้านี้</h2><p className="mt-1 text-sm text-amber-800">เลือกเมนูหลักใหม่จากช่อง “อยู่ใต้เมนู” เพื่อจัดโครงสร้างอีกครั้ง</p><div className="mt-4 space-y-3">{orphans.map((item) => <MenuEditor key={item.id} item={item} roots={roots} />)}</div></section>}</div>{totalPages > 1 && <nav className="mt-7 flex flex-wrap justify-center gap-2" aria-label="เปลี่ยนหน้าเมนู">{Array.from({ length: totalPages }, (_, index) => index + 1).map((value) => <Link key={value} href={`/admin/menu?page=${value}`} className={`rounded-lg border px-3 py-2 text-sm ${value === currentPage ? "border-[var(--primary)] bg-[var(--primary)] text-white" : "border-[var(--border)] bg-white"}`}>{value}</Link>)}</nav>}</>;
}
